### ISSUE TITLE
npm and git depends on ssh

### ISSUE THREAD

**Issue by koresar** [nodesource/docker-node#26] opened 2015-10-01 13:25 UTC
`package.json` urls like `git+ssh://github...` do not work. Packages can't be installed.

**Comment by wblankenship** [comment] 2015-10-02 22:31
duplicate of https://github.com/nodesource/docker-node/issues/8

Will deploy new versions this weekend.

**Comment by wblankenship** [comment] 2015-10-02 22:31
Thanks for opening an issue @koresar, I'll keep you posted on the status through #8 :smile:

**Closed by wblankenship** 2015-10-02 22:31 UTC

**Comment by koresar** [comment] 2015-10-02 23:18
Thank you.
